image: python:3.5.1
pipelines:
  branches:
    master:
      - step:
        script: 
          - pipe: atlassian/aws-s3-deploy:0.3.8
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'ap-southeast-2'
              S3_BUCKET: 'maba-static-site'
              LOCAL_PATH: $BIT_BUCKET_CLONE_DIR
              ACL: 'public-read'
              # DELETE_FLAG: "true"

              