baseurl = "//maba.org.au/" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
title = "Moths and Butterfly Australasia"
theme = "hugo-universal-theme"
relURL = true
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
# disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

[menu]

# Main menus

## HOME
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "About Us"
    identifier = "menu.about"
    url        = "/about/aboutus/"
    weight     = 1
    parent     = "menu.home"


    [[params.main]]
    name       = "About Us"
    identifier = "menu.home.allabout"
    url        = "/allabout/"
    parent     = "menu.home"
    weight     = 1

[[menu.main]]
    name       = "Contact us"
    url        = "/contact/"
    weight     = 1
    parent     = "menu.home"

## MEMBERSHIP
[[menu.main]]
    name       = "Membership"
    identifier = "menu.membership"
    url        = ""
    weight     = 3

    [[menu.main]]
    name       = "About Membership"
    url        = "/membership/home/"
    weight     = 1
    parent     = "menu.membership"

    [[menu.main]]
    name       = "Join MABA"
    url        = "/membership/newmembers/"
    weight     = 2
    parent     = "menu.membership"

    [[menu.main]]
    name       = "Membership categories"
    url        = "/membership/membership_categories/"
    weight     = 3
    parent     = "menu.membership"

    [[menu.main]]
    name       = "Donate to MABA"
    url        = "/membership/member_donations/"
    weight     = 4
    parent     = "menu.membership"

    [[menu.main]]
    name       = "Code of conduct"
    # identifier = "section.ap-home"
    url        = "/mebership/code_of_conduct/"
    weight     = 5
    parent     = "menu.membership"


#[[menu.main]]
#    name       = "Membership"
#    identifier = "section.membership"
#    url        = ""
#    weight     = 1
#    parent     = "menu.membership"
#    post       = 1
#
#[[menu.main]]
#    name       = "Benefits"
#    url        = "/membership/benefits/"
#    weight     = 2
#    parent     = "section.membership"
#

#[[menu.main]]
#    name       = "Subscription fees"
#    url        = "/membership/subscription_fees/"
#    weight     = 4
#    parent     = "section.membership"
#
#[[menu.main]]
#    name       = "Membership form"
#    identifier = "section.membership.form"
#    url        = ""
#    weight     = 2
#    parent     = "menu.membership"
#    post       = 2
#
#[[menu.main]]
#    name       = "New members"
#    url        = "https://docs.google.com/viewer?url=https://raw.githubusercontent.com/stiatragul/maba.org.au/master/documents/2022MABA_membership_application_form_digital.pdf"
#    weight     = 1
#    parent     = "section.membership.form"

#[[menu.main]]
#    name       = "Member renewal"
#    url        = "https://somelink.com"
#    weight     = 2
#    parent     = "section.membership.form"

## GRANTS

[[menu.main]]
    name       = "grants"
    identifier = "menu.grants"
    url        = ""
    weight     = 3
    
[[menu.main]]
    name       = "Grant Information"
    identifier = "section.grantinformation"
    url        = ""
    weight     = 1
    parent     = "menu.grants"
    post       = 1


[[menu.main]]
    name       = "About MABA Grants"
    url        = "/grants/aboutgrants/"
    weight     = 1
    parent     = "section.grantinformation"
    post       = 1

#[[menu.main]]
#   name       = "Donate to Grants"
#    url        = "/grants/donate/"
#    weight     = 2
#    parent     = "section.grantinformation"
#    post       = 1



[[menu.main]]
    name       = "Available Grants"
    identifier = "section.availablegrants"
    url        = ""
    weight     = 2
    parent     = "menu.grants"
     post       = 2

    [[menu.main]]
    name       = "Australian Lepidoptera Research Endowment"
    url        = "/alre/home/"
    weight     = 2
    parent     = "section.availablegrants"

    [[menu.main]]
    name       = "MABA Biodiversity Fund"
    url        = "/grants/available_grants/biodiversity_fund/"
    weight     = 2
    parent     = "section.availablegrants"


## PROJECTS
[[menu.main]]
    name       = "Projects"
    identifier = "menu.projects"
    url        = ""
    weight     = 4

    [[menu.main]]
    name       = "MABA Projects"
    identifier = "section.MABA.projects"
    url        = ""
    weight     = 1
    parent     = "menu.projects"
    post       = 1


[[menu.main]]
    name       = "Butterflies Australia"
    url        = "/projects/MABA_Projects/butterflies_australia/"
    weight     = 1
    parent     = "section.MABA.projects"

## EVENTS
[[menu.main]]
    name       = "Events"
    identifier = "menu.events"
    url        = ""
    weight     = 4

#[[menu.main]]
#    name       = "Meetings"
#    # identifier = "section.ap-home"
#    url        = "/events/meetings/"
#    weight     = 1
#    parent     = "menu.events"
#    post       = 1


[[menu.main]]
    name       = "ANIC moth workshops"
    # identifier = "section.ap-home"
    url        = "/events/anic_moth_workshop/"
    weight     = 2
    parent     = "menu.events"
    post       = 1

[[menu.main]]
    name       = "ANIC moth workshops"
    # identifier = "section.ap-home"
    url        = "/events/anic_moth_workshop/"
    weight     = 3
    parent     = "menu.events"
    post       = 1

[[menu.main]]
    name       = "Next meeting"
    # identifier = "section.ap-home"
    url        = "/events/next_meeting/"
    weight     = 4
    parent     = "menu.events"
    post       = 1

#[[menu.main]]
#    name       = "Butterflies Australia"
#    identifier = "butterfly_australia"
#    url        = "https://www.butterflies.org.au/external/home"
#    weight     = 4.5

## PUBLICATIONS
[[menu.main]]
    name       = "Publications"
    identifier = "menu.publications"
    url        = ""
    weight     = 5

    [[menu.main]]
    name       = "MABA Publications"
    url        = "/publications/newsletters"
    weight     = 1
    parent     = "menu.publications"
    post       = 1

    [[menu.main]]
    name       = "Other Publications"
    url        = "/publications/archived"
    weight     = 2
    parent     = "menu.publications"
    post       = 1

## RESOURCES LINKS
[[menu.main]]
    name       = "Resources"
    identifier = "menu.resources"
    url        = ""
    weight     = 6

[[menu.main]]
    name       = "Identification Resources"
    identifier = "section.id"
    url        = ""
    weight     = 1
    parent     = "menu.resources"
    post       = 1

    [[menu.main]]
        name       = "Australian Moths Online"
        url        = "https://moths.csiro.au/"
        weight     = 1
        parent     = "section.id"
        post       = 1

    [[menu.main]]
        name       = "The caterpillar key"
        url        = "https://keys.lucidcentral.org/keys/v3/the-caterpillar-key/"
        weight     = 2
        parent     = "section.id"

        [[menu.main]]
        name       = "Larger Moths of New Zealand"
        url        = "https://oldwww.landcareresearch.co.nz/resources/identification/animals/large-moths/image-gallery"
        weight     = 2
        parent     = "section.id"
    
         [[menu.main]]
        name       = "Australian Caterpillars and their Butterflies and Moths"
        url        = "http://lepidoptera.butterflyhouse.com.au/faqs/ident.html"
        weight     = 2
        parent     = "section.id"

[[menu.main]]
    name       = "Lepidoptera Societies"
    identifier = "section.lepsoc"
    url        = ""
    weight     = 3
    parent     = "menu.resources"
    post       = 2

    [[menu.main]]
        name       = "Lepidopterists' Society"
        url        = "https://www.lepsoc.org/"
        weight     = 2
        parent     = "section.lepsoc"
        post       = 1
    
    [[menu.main]]
        name       = "Butterfly and Other Invertebrates Club"
        url        = "http://www.boic.org.au/"
        weight     = 4
        parent     = "section.lepsoc"
        post       = 1

[[menu.main]]
    name       = "MABA Member Bodies"
    identifier = "section.membo"
    url        = ""
    weight     = 1
    parent     = "menu.resources"
    post       = 3

    [[menu.main]]
        name       = "Moths and Butterflies of New Zealand Trust"
        url        = "https://www.nzbutterflies.org.nz/"
        weight     = 1
        parent     = "section.membo"
        post       = 1
    
    [[menu.main]]
        name       = "Butterfly Conservation South Australia"
        url        = "https://butterflyconservationsa.net.au/ "
        weight     = 2
        parent     = "section.membo"
        post       = 1

#[[menu.main]]
#    name       = "Australian Moths Online"
#    url        = "https://moths.csiro.au/"
#    weight     = 1
#    parent     = "menu.resources"
#    post       = 1
#
#[[menu.main]]
#    name       = "Lepidopterists' Society"
#    url        = "https://www.lepsoc.org/"
#    weight     = 2
#    parent     = "menu.resources"
#    post       = 1
#
#[[menu.main]]
#    name       = "The caterpillar key"
#    url        = "https://keys.lucidcentral.org/keys/v3/the-caterpillar-key/"
#    weight     = 3
#    parent     = "menu.resources"
#    post       = 1
#
#[[menu.main]]
#    name       = "Australian Lepidoptera Research Endowment"
#    url        = "https://www.australianlepidopteraendowment.com/"
#    weight     = 5
#    parent     = "menu.resources"
#    post       = 1
#
#[[menu.main]]
#    name       = "National Moth Week"
#    url        = "https://nationalmothweek.org/"
#    weight     = 6
#    parent     = "menu.resources"
#    post       = 1
#
#[[menu.main]]
#    name       = "Moths and Butterflies of New Zealand Trust"
#    url        = "https://www.nzbutterflies.org.nz/"
#    weight     = 7
#    parent     = "menu.resources"
#    post       = 1
#
#[[menu.main]]
#    name       = "Butterfly and Other Invertebrates Club"
#    url        = "http://www.boic.org.au/"
#    weight     = 8
#    parent     = "menu.resources"
#    post       = 1
#
#[[menu.main]]
#    name       = "Butterflies Conservation South Australia"
#    url        = "https://butterflyconservationsa.net.au/ "
#    weight     = 9
#    parent     = "menu.resources"
#    post       = 1
#
## ALRE
#[[menu.main]]
#    name       = "ALRE"
#    identifier = "menu.alre"
#    url        = ""
#    weight     = 6.5
#
#[[menu.main]]
#    name       = "ALRE Home"
#    url        = "/alre/home/"
#    weight     = 1
#    parent     = "menu.alre"
#    post       = 1
#
#[[menu.main]]
#    name       = "Supporting research"
#    url        = "/alre/support/"
#    identifier = "menu.alre.support"
#    weight     = 1
#    parent     = "menu.alre"
#    post       = 1
#
#[[menu.main]]
#    name       = "Donors"
#    url        = "/alre/donors"
#    weight     = 4
#    parent     = "menu.alre"
#    post       = 1
#
#[[menu.main]]
#    name       = "Donations"
#    url        = "/alre/donations"
#    weight     = 3
#    parent     = "menu.alre"
#    post       = 1
#
#[[menu.main]]
#    name       = "Grants"
#    url        = "/alre/grants"
#    weight     = 2
#    parent     = "menu.alre"
#    post       = 1


## ABOUT 

#[[menu.main]]
#    name       = "Our society"
#    url        = "/about/society/"
#    weight     = 1
#    parent     = "menu.about"
#    post       = 1
#
#[[menu.main]]
#    name       = "Office bearers"
#    url        = "/about/office_bearers/"
#    weight     = 2
#    parent     = "menu.about"
#    post       = 1
#
#[[menu.main]]
#    name       = "Constitution"
#    url        = "https://docs.google.com/viewer?url=https://raw.githubusercontent.com/stiatragul/maba.org.au/master/documents/MABA_Constitution.pdf"
#    weight     = 3
#    parent     = "menu.about"
#    post       = 1
#
#[[menu.main]]
#    name       = "Logo"
#    url        = "/about/logo/"
#    weight     = 4
#    parent     = "menu.about"
#    post       = 1

## Blog
# [[menu.main]]
#    name       = "Blog"
#    identifier = "menu.blog"
#    url        = "/blog/"
#    weight     = 5

## PROJECTS
#[[menu.main]]
#    name       = "Projects"
#    identifier = "menu.projects"
#    url        = "/projects/"
#    weight     = 6

# [[menu.main]]
#     name       = "FAQ"
#     identifier = "menu.faq"
#     url        = "/faq/"
#     weight     = 7

# [[menu.main]]
#     identifier = "contact"
#     name       = "Contact"
#     url        = "/contact/"
#     weight     = 8


# Top bar social links menu

# [[menu.topbar]]
#     weight = 2
#     name = "GitHub"
#     url = "https://github.com/"
#     pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
   weight = 3
   name = "Facebook"
   url = "https://www.facebook.com/profile.php?id=100087437239315"
   pre = "<i class='fab fa-2x fa-facebook'></i>"

# [[menu.topbar]]
#    weight = 4
#    name = "Twitter"
#    url = "http://twitter.com"
#    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:enquiries@maba.org.au"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

### PARAMS

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devcows", "hugo", "go"]
    mainSections = ["home"]
    defaultDescription = "Moths and Butterflies Australasia"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    # enableGoogleMaps = true
    # googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    # latitude = "-12.043333"
    # longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = ""

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    # formspree_action = "https://formspree.io/sample/of/endpoint"
    # contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>Moths and Butterflies Australasia (MABA) is a not-for-profit organisation with charitable status.</p><p> <b>Contact us at: enquiries@maba.org.au</b></p>"
    copyright = "Copyright (c) 2022, Moth and Butterflies Australasia; all rights reserved."
    
    # Format dates with Go's time formatting
    date_format = "2 January, 2006"

    disabled_logo = false
    logo_text = "Moths and Butterflies Australasia"

    logo = "img/logo/maba_w_text.png"
    logo_small = "img/logo/MABA-Logo-Circle-Colour-transparent-inner-BLACK_TEXT.png"
    
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Moths and Butterflies Australasia Inc.</strong>
        <br>c/o Division of Ecology and Evolution, 
        <br>Research School of Biology, 
        <br>RN Robertson Building, 
        <br>46 Sullivans Creek Rd
        <br>Australian National University
        <br>ACTON ACT 2601
        <br>
        <strong>Australia</strong>
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us: enquiries@maba.org.au</p>
      <a href="mailto:enquiries@maba.org.au" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 4000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

# No need testimonial
[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Check out the latest project MABA sponsors"
    hide_summary = false

[params.footer.recent_posts]
    enable = false

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"


[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
